# Generated by Django 5.1.1 on 2024-11-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sugerencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugerencias',
            options={'verbose_name_plural': 'Sugerencias'},
        ),
    ]
